//! `REACH_TEST_MODE`: a canned report, so the AISE integration and UI can be
//! exercised end to end without an inference server or a repository.
//!
//! The report always has the shape of the most interesting real outcome —
//! `direct_references` with one labelled occurrence — because that is the
//! one that exercises every part of the report view. Nothing in it was
//! observed: no advisory was read by a model and no code was fetched. Every
//! analyst-facing string says so, and [`Report::test_mode`] lets a client
//! label it without parsing prose.

use std::time::Duration;

use crate::models::{
    Counters, EvidenceSite, PriorityLabel, RelevanceLabel, Report, Ruleset, StageOutcome,
    StageStatus, EVIDENCE_DISCLAIMER, REPORT_SCHEMA_VERSION,
};

use super::AnalysisJob;

/// How long a test-mode analysis "runs" before completing.
pub const DELAY: Duration = Duration::from_secs(2);

const NOT_RUN: &str = "Not run — REACH_TEST_MODE is set; this report is canned.";

/// The fixed report. The example symbol is derived from the job's package
/// name so the line reads plausibly next to the finding it is attached to.
pub fn canned_report(job: &AnalysisJob) -> Report {
    let package = job
        .package_name
        .as_deref()
        .map(str::trim)
        .filter(|p| !p.is_empty())
        .unwrap_or("example_package");
    let term = format!("{package}.vulnerable_call");
    let advisory = job.osv_id.as_deref().unwrap_or("the advisory");

    let mut stages: Vec<StageOutcome> = [
        ("A", "package presence"),
        ("B", "advisory ruleset"),
        ("C", "occurrence search"),
        ("D", "occurrence scoring"),
    ]
    .into_iter()
    .map(|(stage, name)| StageOutcome::new(stage, name, StageStatus::Skipped, NOT_RUN, 0))
    .collect();
    stages.push(StageOutcome::new(
        "E",
        "rubric",
        StageStatus::Ok,
        "Test mode: priority fixed to direct_references.",
        0,
    ));

    let priority = PriorityLabel::DirectReferences;
    Report {
        schema_version: REPORT_SCHEMA_VERSION,
        analysis_id: job.id,
        priority,
        priority_description: priority.describe().to_string(),
        rubric_trace: vec![
            "TEST MODE: priority fixed to direct_references; no rubric rule was evaluated."
                .to_string(),
        ],
        ruleset: Some(Ruleset {
            vulnerable_symbols: vec![term.clone()],
            summary: format!(
                "TEST MODE — canned report for {advisory}. The advisory was not read by a model \
                 and no code was scanned."
            ),
            notes: vec!["Generated by REACH_TEST_MODE; not extracted from any advisory.".to_string()],
            ..Default::default()
        }),
        package_present: Some(true),
        package_evidence: vec![
            "TEST MODE: placeholder — not observed in any repository.".to_string(),
        ],
        sites: vec![EvidenceSite {
            path: "reach-test-mode/example.py".to_string(),
            line: 42,
            term: term.clone(),
            snippet: format!(
                "result = {term}(user_input)  # example line generated by REACH_TEST_MODE"
            ),
            label: Some(RelevanceLabel::LikelyRelevant),
            reasoning: "TEST MODE placeholder: this occurrence was generated, not found. It \
                        exists so the report view can be exercised without an inference server."
                .to_string(),
            // Nothing was checked out, so nothing was verified.
            citation_verified: false,
        }],
        stages,
        counters: Counters {
            occurrences_found: 1,
            occurrences_reported: 1,
            ..Default::default()
        },
        disclaimer: EVIDENCE_DISCLAIMER.to_string(),
        test_mode: true,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn job(package: Option<&str>) -> AnalysisJob {
        AnalysisJob {
            id: uuid::Uuid::new_v4(),
            advisory_text: "irrelevant".to_string(),
            osv_id: Some("CVE-2017-18342".to_string()),
            package_name: package.map(str::to_string),
            ecosystem: None,
            repo_url: Some("https://github.com/example/does-not-exist".to_string()),
            commit: Some("a".repeat(40)),
            subpath: None,
        }
    }

    #[test]
    fn the_canned_report_is_a_direct_reference_with_one_example_line() {
        let j = job(Some("pyyaml"));
        let r = canned_report(&j);
        assert!(r.test_mode);
        assert_eq!(r.analysis_id, j.id);
        assert_eq!(r.priority, PriorityLabel::DirectReferences);
        assert_eq!(r.sites.len(), 1);
        assert_eq!(r.sites[0].term, "pyyaml.vulnerable_call");
        assert_eq!(r.sites[0].label, Some(RelevanceLabel::LikelyRelevant));
        // Nothing was checked out, so it must never claim a verified citation.
        assert!(!r.sites[0].citation_verified);
        assert_eq!(r.disclaimer, EVIDENCE_DISCLAIMER);
    }

    #[test]
    fn it_names_itself_wherever_an_analyst_reads() {
        let r = canned_report(&job(None));
        assert!(r.ruleset.as_ref().unwrap().summary.starts_with("TEST MODE"));
        assert!(r.sites[0].reasoning.starts_with("TEST MODE"));
        assert!(r.rubric_trace[0].starts_with("TEST MODE"));
        assert_eq!(r.sites[0].term, "example_package.vulnerable_call");
        // The serialized form carries the flag, which is what AISE archives.
        let json = serde_json::to_value(&r).unwrap();
        assert_eq!(json["test_mode"], true);
    }

    #[tokio::test]
    async fn the_pipeline_returns_it_without_touching_the_fetcher() {
        use crate::fetcher::{Checkout, FetchError, RepoFetcher};
        use std::sync::Arc;

        struct MustNotFetch;
        #[async_trait::async_trait]
        impl RepoFetcher for MustNotFetch {
            async fn fetch(&self, _u: &str, _c: &str) -> Result<Checkout, FetchError> {
                panic!("test mode must not fetch")
            }
        }

        let deps = super::super::PipelineDeps {
            client: crate::ai::ChatClient::new(crate::config::AiConfig {
                base_url: "http://127.0.0.1:1".into(),
                model: "test".into(),
                api_key: None,
                timeout: Duration::from_millis(100),
                max_tokens: 16,
                temperature: 0.0,
            }),
            git: Arc::new(MustNotFetch),
            local: Arc::new(MustNotFetch),
            limits: crate::config::Limits {
                max_repo_mb: 1,
                max_sites: 1,
                max_scored_sites: 1,
                max_file_kb: 1,
                max_advisory_chars: 100,
            },
            test_mode: true,
        };
        let r = super::super::run(&deps, &job(Some("pyyaml"))).await.unwrap();
        assert!(r.test_mode);
        assert_eq!(r.counters.inference_calls, 0);
    }
}
