[package]
name = "magnolia-api"
version.workspace = true
edition.workspace = true

[[bin]]
name = "magnolia-server"
path = "src/main.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
chrono.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
sha2.workspace = true
hex.workspace = true
tower-http.workspace = true
semver.workspace = true
async-trait = "0.1"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio", "migrate"] }
tar = "0.4"

magnolia-core = { path = "../core" }
magnolia-auth = { path = "../auth" }
magnolia-signer = { path = "../signer" }
magnolia-storage = { path = "../storage" }
magnolia-db = { path = "../db" }
magnolia-audit = { path = "../audit" }
magnolia-dtrack = { path = "../dtrack" }
magnolia-osv = { path = "../osv" }
magnolia-depsdev = { path = "../depsdev" }
